### ISSUE TITLE
Dups

### ISSUE THREAD

**Issue by iandoug** [JonReagan/pykblayoutoptimizer#1]
Hi

Well it's very fast, but gave me a layout with 2 k's and no v.

You don't seem to be taking same-finger bigrams into account.

Cheers, Ian

**Comment by JonReagan** [comment]
Thanks for catching that, Ian, I'll take a look.  Same-finger bigrams.. What is that?  Sounds interesting!   

All the best,
Jon

**Comment by iandoug** [comment]
2. Same-finger bigrams.
- Successive keys typed with the same finger should be avoided. Also known as same-finger bigrams, these cause disruption the typist's natural flow

https://kennetchaz.github.io/symmetric-typing/layouts.html

**Comment by JonReagan** [comment]
Very cool!  Thanks for sending the link.  I learned something new today.  I initiated a new pull request to fix the key issue - I had a duplicate entry on the layout for the 21st most common letter. It seems to be working now.

**Comment by iandoug** [comment]
Had another go. The input is 1 MB of chained English bigrams, which mimics written English.

Your outer letters are not bad, but the two index fingers are terrible. 

You can't just allocate letters in order of frequency to best remaining spot. You need to consider same-finger bigrams.

Also, leaving the right pinky on semicolon is a bit of a waste :-)

![pykblayoutoptimizer-monkey7](https://user-images.githubusercontent.com/12673886/123524689-5143c380-d6cc-11eb-9a4c-d260361ab581.png)

Cheers, Ian

**Comment by JonReagan** [comment]
Thanks for giving it another go, Ian!  I'm looking for ways to include consideration for same-finger bigrams in the next release.
